begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.solr.client.solrj.request
package|package
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|client
operator|.
name|solrj
operator|.
name|request
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Date
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|common
operator|.
name|util
operator|.
name|NamedList
import|;
end_import

begin_class
DECL|class|CoreStatus
specifier|public
class|class
name|CoreStatus
block|{
DECL|field|response
specifier|private
specifier|final
name|NamedList
argument_list|<
name|Object
argument_list|>
name|response
decl_stmt|;
DECL|method|CoreStatus
specifier|public
name|CoreStatus
parameter_list|(
name|NamedList
argument_list|<
name|Object
argument_list|>
name|response
parameter_list|)
block|{
name|this
operator|.
name|response
operator|=
name|response
expr_stmt|;
block|}
DECL|method|getDataDirectory
specifier|public
name|String
name|getDataDirectory
parameter_list|()
block|{
return|return
operator|(
name|String
operator|)
name|response
operator|.
name|get
argument_list|(
literal|"dataDir"
argument_list|)
return|;
block|}
DECL|method|getInstanceDirectory
specifier|public
name|String
name|getInstanceDirectory
parameter_list|()
block|{
return|return
operator|(
name|String
operator|)
name|response
operator|.
name|findRecursive
argument_list|(
literal|"instanceDir"
argument_list|)
return|;
block|}
annotation|@
name|Override
DECL|method|toString
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|response
operator|.
name|toString
argument_list|()
return|;
block|}
DECL|method|getCoreStartTime
specifier|public
name|Date
name|getCoreStartTime
parameter_list|()
block|{
return|return
operator|(
name|Date
operator|)
name|response
operator|.
name|get
argument_list|(
literal|"startTime"
argument_list|)
return|;
block|}
block|}
end_class

end_unit

