begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.lucene.index
package|package
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|search
operator|.
name|DocIdSetIterator
import|;
end_import

begin_comment
comment|// javadocs
end_comment

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|util
operator|.
name|PriorityQueue
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|search
operator|.
name|DocIdSetIterator
operator|.
name|NO_MORE_DOCS
import|;
end_import

begin_comment
comment|/** Utility class to help merging documents from sub-readers according to either simple  *  concatenated (unsorted) order, or by a specified index-time sort, skipping  *  deleted documents and remapping non-deleted documents. */
end_comment

begin_class
DECL|class|DocIDMerger
specifier|public
specifier|abstract
class|class
name|DocIDMerger
parameter_list|<
name|T
extends|extends
name|DocIDMerger
operator|.
name|Sub
parameter_list|>
block|{
comment|/** Represents one sub-reader being merged */
DECL|class|Sub
specifier|public
specifier|static
specifier|abstract
class|class
name|Sub
block|{
comment|/** Mapped doc ID */
DECL|field|mappedDocID
specifier|public
name|int
name|mappedDocID
decl_stmt|;
DECL|field|docMap
specifier|final
name|MergeState
operator|.
name|DocMap
name|docMap
decl_stmt|;
comment|/** Sole constructor */
DECL|method|Sub
specifier|public
name|Sub
parameter_list|(
name|MergeState
operator|.
name|DocMap
name|docMap
parameter_list|)
block|{
name|this
operator|.
name|docMap
operator|=
name|docMap
expr_stmt|;
block|}
comment|/** Returns the next document ID from this sub reader, and {@link DocIdSetIterator#NO_MORE_DOCS} when done */
DECL|method|nextDoc
specifier|public
specifier|abstract
name|int
name|nextDoc
parameter_list|()
throws|throws
name|IOException
function_decl|;
block|}
comment|/** Construct this from the provided subs, specifying the maximum sub count */
DECL|method|of
specifier|public
specifier|static
parameter_list|<
name|T
extends|extends
name|DocIDMerger
operator|.
name|Sub
parameter_list|>
name|DocIDMerger
argument_list|<
name|T
argument_list|>
name|of
parameter_list|(
name|List
argument_list|<
name|T
argument_list|>
name|subs
parameter_list|,
name|int
name|maxCount
parameter_list|,
name|boolean
name|indexIsSorted
parameter_list|)
throws|throws
name|IOException
block|{
if|if
condition|(
name|indexIsSorted
operator|&&
name|maxCount
operator|>
literal|1
condition|)
block|{
return|return
operator|new
name|SortedDocIDMerger
argument_list|<>
argument_list|(
name|subs
argument_list|,
name|maxCount
argument_list|)
return|;
block|}
else|else
block|{
return|return
operator|new
name|SequentialDocIDMerger
argument_list|<>
argument_list|(
name|subs
argument_list|)
return|;
block|}
block|}
comment|/** Construct this from the provided subs */
DECL|method|of
specifier|public
specifier|static
parameter_list|<
name|T
extends|extends
name|DocIDMerger
operator|.
name|Sub
parameter_list|>
name|DocIDMerger
argument_list|<
name|T
argument_list|>
name|of
parameter_list|(
name|List
argument_list|<
name|T
argument_list|>
name|subs
parameter_list|,
name|boolean
name|indexIsSorted
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|of
argument_list|(
name|subs
argument_list|,
name|subs
operator|.
name|size
argument_list|()
argument_list|,
name|indexIsSorted
argument_list|)
return|;
block|}
comment|/** Reuse API, currently only used by postings during merge */
DECL|method|reset
specifier|public
specifier|abstract
name|void
name|reset
parameter_list|()
throws|throws
name|IOException
function_decl|;
comment|/** Returns null when done.    *<b>NOTE:</b> after the iterator has exhausted you should not call this    *  method, as it may result in unpredicted behavior. */
DECL|method|next
specifier|public
specifier|abstract
name|T
name|next
parameter_list|()
throws|throws
name|IOException
function_decl|;
DECL|method|DocIDMerger
specifier|private
name|DocIDMerger
parameter_list|()
block|{}
DECL|class|SequentialDocIDMerger
specifier|private
specifier|static
class|class
name|SequentialDocIDMerger
parameter_list|<
name|T
extends|extends
name|DocIDMerger
operator|.
name|Sub
parameter_list|>
extends|extends
name|DocIDMerger
argument_list|<
name|T
argument_list|>
block|{
DECL|field|subs
specifier|private
specifier|final
name|List
argument_list|<
name|T
argument_list|>
name|subs
decl_stmt|;
DECL|field|current
specifier|private
name|T
name|current
decl_stmt|;
DECL|field|nextIndex
specifier|private
name|int
name|nextIndex
decl_stmt|;
DECL|method|SequentialDocIDMerger
specifier|private
name|SequentialDocIDMerger
parameter_list|(
name|List
argument_list|<
name|T
argument_list|>
name|subs
parameter_list|)
throws|throws
name|IOException
block|{
name|this
operator|.
name|subs
operator|=
name|subs
expr_stmt|;
name|reset
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|reset
specifier|public
name|void
name|reset
parameter_list|()
throws|throws
name|IOException
block|{
if|if
condition|(
name|subs
operator|.
name|size
argument_list|()
operator|>
literal|0
condition|)
block|{
name|current
operator|=
name|subs
operator|.
name|get
argument_list|(
literal|0
argument_list|)
expr_stmt|;
name|nextIndex
operator|=
literal|1
expr_stmt|;
block|}
else|else
block|{
name|current
operator|=
literal|null
expr_stmt|;
name|nextIndex
operator|=
literal|0
expr_stmt|;
block|}
block|}
annotation|@
name|Override
DECL|method|next
specifier|public
name|T
name|next
parameter_list|()
throws|throws
name|IOException
block|{
while|while
condition|(
literal|true
condition|)
block|{
name|int
name|docID
init|=
name|current
operator|.
name|nextDoc
argument_list|()
decl_stmt|;
if|if
condition|(
name|docID
operator|==
name|NO_MORE_DOCS
condition|)
block|{
if|if
condition|(
name|nextIndex
operator|==
name|subs
operator|.
name|size
argument_list|()
condition|)
block|{
name|current
operator|=
literal|null
expr_stmt|;
return|return
literal|null
return|;
block|}
name|current
operator|=
name|subs
operator|.
name|get
argument_list|(
name|nextIndex
argument_list|)
expr_stmt|;
name|nextIndex
operator|++
expr_stmt|;
continue|continue;
block|}
name|int
name|mappedDocID
init|=
name|current
operator|.
name|docMap
operator|.
name|get
argument_list|(
name|docID
argument_list|)
decl_stmt|;
if|if
condition|(
name|mappedDocID
operator|!=
operator|-
literal|1
condition|)
block|{
name|current
operator|.
name|mappedDocID
operator|=
name|mappedDocID
expr_stmt|;
return|return
name|current
return|;
block|}
block|}
block|}
block|}
DECL|class|SortedDocIDMerger
specifier|private
specifier|static
class|class
name|SortedDocIDMerger
parameter_list|<
name|T
extends|extends
name|DocIDMerger
operator|.
name|Sub
parameter_list|>
extends|extends
name|DocIDMerger
argument_list|<
name|T
argument_list|>
block|{
DECL|field|subs
specifier|private
specifier|final
name|List
argument_list|<
name|T
argument_list|>
name|subs
decl_stmt|;
DECL|field|queue
specifier|private
specifier|final
name|PriorityQueue
argument_list|<
name|T
argument_list|>
name|queue
decl_stmt|;
DECL|method|SortedDocIDMerger
specifier|private
name|SortedDocIDMerger
parameter_list|(
name|List
argument_list|<
name|T
argument_list|>
name|subs
parameter_list|,
name|int
name|maxCount
parameter_list|)
throws|throws
name|IOException
block|{
name|this
operator|.
name|subs
operator|=
name|subs
expr_stmt|;
name|queue
operator|=
operator|new
name|PriorityQueue
argument_list|<
name|T
argument_list|>
argument_list|(
name|maxCount
argument_list|)
block|{
annotation|@
name|Override
specifier|protected
name|boolean
name|lessThan
parameter_list|(
name|Sub
name|a
parameter_list|,
name|Sub
name|b
parameter_list|)
block|{
assert|assert
name|a
operator|.
name|mappedDocID
operator|!=
name|b
operator|.
name|mappedDocID
assert|;
return|return
name|a
operator|.
name|mappedDocID
operator|<
name|b
operator|.
name|mappedDocID
return|;
block|}
block|}
expr_stmt|;
name|reset
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|reset
specifier|public
name|void
name|reset
parameter_list|()
throws|throws
name|IOException
block|{
comment|// caller may not have fully consumed the queue:
name|queue
operator|.
name|clear
argument_list|()
expr_stmt|;
name|boolean
name|first
init|=
literal|true
decl_stmt|;
for|for
control|(
name|T
name|sub
range|:
name|subs
control|)
block|{
if|if
condition|(
name|first
condition|)
block|{
comment|// by setting mappedDocID = -1, this entry is guaranteed to be the top of the queue
comment|// so the first call to next() will advance it
name|sub
operator|.
name|mappedDocID
operator|=
operator|-
literal|1
expr_stmt|;
name|first
operator|=
literal|false
expr_stmt|;
block|}
else|else
block|{
name|int
name|mappedDocID
decl_stmt|;
while|while
condition|(
literal|true
condition|)
block|{
name|int
name|docID
init|=
name|sub
operator|.
name|nextDoc
argument_list|()
decl_stmt|;
if|if
condition|(
name|docID
operator|==
name|NO_MORE_DOCS
condition|)
block|{
name|mappedDocID
operator|=
name|NO_MORE_DOCS
expr_stmt|;
break|break;
block|}
name|mappedDocID
operator|=
name|sub
operator|.
name|docMap
operator|.
name|get
argument_list|(
name|docID
argument_list|)
expr_stmt|;
if|if
condition|(
name|mappedDocID
operator|!=
operator|-
literal|1
condition|)
block|{
break|break;
block|}
block|}
if|if
condition|(
name|mappedDocID
operator|==
name|NO_MORE_DOCS
condition|)
block|{
comment|// all docs in this sub were deleted; do not add it to the queue!
continue|continue;
block|}
name|sub
operator|.
name|mappedDocID
operator|=
name|mappedDocID
expr_stmt|;
block|}
name|queue
operator|.
name|add
argument_list|(
name|sub
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Override
DECL|method|next
specifier|public
name|T
name|next
parameter_list|()
throws|throws
name|IOException
block|{
name|T
name|top
init|=
name|queue
operator|.
name|top
argument_list|()
decl_stmt|;
while|while
condition|(
literal|true
condition|)
block|{
name|int
name|docID
init|=
name|top
operator|.
name|nextDoc
argument_list|()
decl_stmt|;
if|if
condition|(
name|docID
operator|==
name|NO_MORE_DOCS
condition|)
block|{
name|queue
operator|.
name|pop
argument_list|()
expr_stmt|;
name|top
operator|=
name|queue
operator|.
name|top
argument_list|()
expr_stmt|;
break|break;
block|}
name|int
name|mappedDocID
init|=
name|top
operator|.
name|docMap
operator|.
name|get
argument_list|(
name|docID
argument_list|)
decl_stmt|;
if|if
condition|(
name|mappedDocID
operator|==
operator|-
literal|1
condition|)
block|{
comment|// doc was deleted
continue|continue;
block|}
else|else
block|{
name|top
operator|.
name|mappedDocID
operator|=
name|mappedDocID
expr_stmt|;
name|top
operator|=
name|queue
operator|.
name|updateTop
argument_list|()
expr_stmt|;
break|break;
block|}
block|}
return|return
name|top
return|;
block|}
block|}
block|}
end_class

end_unit

