begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.lucene.search.join
package|package
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|search
operator|.
name|join
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|BinaryDocValues
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|DocValues
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|LeafReader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|LeafReaderContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|SortedSetDocValues
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|search
operator|.
name|SimpleCollector
import|;
end_import

begin_class
DECL|class|DocValuesTermsCollector
specifier|abstract
class|class
name|DocValuesTermsCollector
parameter_list|<
name|DV
parameter_list|>
extends|extends
name|SimpleCollector
block|{
annotation|@
name|FunctionalInterface
DECL|interface|Function
specifier|static
interface|interface
name|Function
parameter_list|<
name|R
parameter_list|>
block|{
DECL|method|apply
name|R
name|apply
parameter_list|(
name|LeafReader
name|t
parameter_list|)
throws|throws
name|IOException
function_decl|;
block|}
DECL|field|docValues
specifier|protected
name|DV
name|docValues
decl_stmt|;
DECL|field|docValuesCall
specifier|private
specifier|final
name|Function
argument_list|<
name|DV
argument_list|>
name|docValuesCall
decl_stmt|;
DECL|method|DocValuesTermsCollector
specifier|public
name|DocValuesTermsCollector
parameter_list|(
name|Function
argument_list|<
name|DV
argument_list|>
name|docValuesCall
parameter_list|)
block|{
name|this
operator|.
name|docValuesCall
operator|=
name|docValuesCall
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|doSetNextReader
specifier|protected
specifier|final
name|void
name|doSetNextReader
parameter_list|(
name|LeafReaderContext
name|context
parameter_list|)
throws|throws
name|IOException
block|{
name|docValues
operator|=
name|docValuesCall
operator|.
name|apply
argument_list|(
name|context
operator|.
name|reader
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|binaryDocValues
specifier|static
name|Function
argument_list|<
name|BinaryDocValues
argument_list|>
name|binaryDocValues
parameter_list|(
name|String
name|field
parameter_list|)
block|{
return|return
parameter_list|(
name|ctx
parameter_list|)
lambda|->
name|DocValues
operator|.
name|getBinary
argument_list|(
name|ctx
argument_list|,
name|field
argument_list|)
return|;
block|}
DECL|method|sortedSetDocValues
specifier|static
name|Function
argument_list|<
name|SortedSetDocValues
argument_list|>
name|sortedSetDocValues
parameter_list|(
name|String
name|field
parameter_list|)
block|{
return|return
parameter_list|(
name|ctx
parameter_list|)
lambda|->
name|DocValues
operator|.
name|getSortedSet
argument_list|(
name|ctx
argument_list|,
name|field
argument_list|)
return|;
block|}
block|}
end_class

end_unit

