begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.lucene.search
package|package
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|search
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|document
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|document
operator|.
name|DoubleRangeField
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|IndexReader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|index
operator|.
name|RandomIndexWriter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|store
operator|.
name|Directory
import|;
end_import

begin_comment
comment|/**  * Random testing for RangeFieldQueries. Testing rigor inspired by {@code BaseGeoPointTestCase}  */
end_comment

begin_class
DECL|class|TestDoubleRangeFieldQueries
specifier|public
class|class
name|TestDoubleRangeFieldQueries
extends|extends
name|BaseRangeFieldQueryTestCase
block|{
DECL|field|FIELD_NAME
specifier|private
specifier|static
specifier|final
name|String
name|FIELD_NAME
init|=
literal|"rangeField"
decl_stmt|;
DECL|method|newRangeField
specifier|protected
name|DoubleRangeField
name|newRangeField
parameter_list|(
name|double
index|[]
name|min
parameter_list|,
name|double
index|[]
name|max
parameter_list|)
block|{
return|return
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
name|min
argument_list|,
name|max
argument_list|)
return|;
block|}
DECL|method|newIntersectsQuery
specifier|protected
name|Query
name|newIntersectsQuery
parameter_list|(
name|double
index|[]
name|min
parameter_list|,
name|double
index|[]
name|max
parameter_list|)
block|{
return|return
name|DoubleRangeField
operator|.
name|newIntersectsQuery
argument_list|(
name|FIELD_NAME
argument_list|,
name|min
argument_list|,
name|max
argument_list|)
return|;
block|}
DECL|method|newContainsQuery
specifier|protected
name|Query
name|newContainsQuery
parameter_list|(
name|double
index|[]
name|min
parameter_list|,
name|double
index|[]
name|max
parameter_list|)
block|{
return|return
name|DoubleRangeField
operator|.
name|newContainsQuery
argument_list|(
name|FIELD_NAME
argument_list|,
name|min
argument_list|,
name|max
argument_list|)
return|;
block|}
DECL|method|newWithinQuery
specifier|protected
name|Query
name|newWithinQuery
parameter_list|(
name|double
index|[]
name|min
parameter_list|,
name|double
index|[]
name|max
parameter_list|)
block|{
return|return
name|DoubleRangeField
operator|.
name|newWithinQuery
argument_list|(
name|FIELD_NAME
argument_list|,
name|min
argument_list|,
name|max
argument_list|)
return|;
block|}
comment|/** Basic test */
DECL|method|testBasics
specifier|public
name|void
name|testBasics
parameter_list|()
throws|throws
name|Exception
block|{
name|Directory
name|dir
init|=
name|newDirectory
argument_list|()
decl_stmt|;
name|RandomIndexWriter
name|writer
init|=
operator|new
name|RandomIndexWriter
argument_list|(
name|random
argument_list|()
argument_list|,
name|dir
argument_list|)
decl_stmt|;
comment|// intersects (within)
name|Document
name|document
init|=
operator|new
name|Document
argument_list|()
decl_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|10.0
block|,
operator|-
literal|10.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|9.1
block|,
literal|10.1
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// intersects (crosses)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
literal|10.0
block|,
operator|-
literal|10.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|20.0
block|,
literal|10.0
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// intersects (contains)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|20.0
block|,
operator|-
literal|20.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|30.0
block|,
literal|30.1
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// intersects (crosses)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11.1
block|,
operator|-
literal|11.2
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|1.23
block|,
literal|11.5
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// intersects (crosses)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
literal|12.33
block|,
literal|1.2
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|15.1
block|,
literal|29.9
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// disjoint
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|122.33
block|,
literal|1.2
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|115.1
block|,
literal|29.9
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// intersects (crosses)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
name|Double
operator|.
name|NEGATIVE_INFINITY
block|,
literal|1.2
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11.0
block|,
literal|29.9
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// equal (within, contains, intersects)
name|document
operator|=
operator|new
name|Document
argument_list|()
expr_stmt|;
name|document
operator|.
name|add
argument_list|(
operator|new
name|DoubleRangeField
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11
block|,
operator|-
literal|15
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|15
block|,
literal|20
block|}
argument_list|)
argument_list|)
expr_stmt|;
name|writer
operator|.
name|addDocument
argument_list|(
name|document
argument_list|)
expr_stmt|;
comment|// search
name|IndexReader
name|reader
init|=
name|writer
operator|.
name|getReader
argument_list|()
decl_stmt|;
name|IndexSearcher
name|searcher
init|=
name|newSearcher
argument_list|(
name|reader
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|7
argument_list|,
name|searcher
operator|.
name|count
argument_list|(
name|DoubleRangeField
operator|.
name|newIntersectsQuery
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11.0
block|,
operator|-
literal|15.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|15.0
block|,
literal|20.0
block|}
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|searcher
operator|.
name|count
argument_list|(
name|DoubleRangeField
operator|.
name|newWithinQuery
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11.0
block|,
operator|-
literal|15.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|15.0
block|,
literal|20.0
block|}
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|searcher
operator|.
name|count
argument_list|(
name|DoubleRangeField
operator|.
name|newContainsQuery
argument_list|(
name|FIELD_NAME
argument_list|,
operator|new
name|double
index|[]
block|{
operator|-
literal|11.0
block|,
operator|-
literal|15.0
block|}
argument_list|,
operator|new
name|double
index|[]
block|{
literal|15.0
block|,
literal|20.0
block|}
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|reader
operator|.
name|close
argument_list|()
expr_stmt|;
name|writer
operator|.
name|close
argument_list|()
expr_stmt|;
name|dir
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

