begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.solr.update.processor
package|package
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|update
operator|.
name|processor
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|SolrTestCaseJ4
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|common
operator|.
name|SolrInputDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|common
operator|.
name|params
operator|.
name|ModifiableSolrParams
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|request
operator|.
name|LocalSolrQueryRequest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|response
operator|.
name|SolrQueryResponse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|update
operator|.
name|AddUpdateCommand
import|;
end_import

begin_class
DECL|class|TemplateUpdateProcessorTest
specifier|public
class|class
name|TemplateUpdateProcessorTest
extends|extends
name|SolrTestCaseJ4
block|{
DECL|method|testSimple
specifier|public
name|void
name|testSimple
parameter_list|()
throws|throws
name|Exception
block|{
name|AddUpdateCommand
name|cmd
init|=
operator|new
name|AddUpdateCommand
argument_list|(
operator|new
name|LocalSolrQueryRequest
argument_list|(
literal|null
argument_list|,
operator|new
name|ModifiableSolrParams
argument_list|()
operator|.
name|add
argument_list|(
literal|"processor"
argument_list|,
literal|"Template"
argument_list|)
operator|.
name|add
argument_list|(
literal|"Template.field"
argument_list|,
literal|"id:${firstName}_${lastName}"
argument_list|)
operator|.
name|add
argument_list|(
literal|"Template.field"
argument_list|,
literal|"another:${lastName}_${firstName}"
argument_list|)
operator|.
name|add
argument_list|(
literal|"Template.field"
argument_list|,
literal|"missing:${lastName}_${unKnown}"
argument_list|)
argument_list|)
argument_list|)
decl_stmt|;
name|cmd
operator|.
name|solrDoc
operator|=
operator|new
name|SolrInputDocument
argument_list|()
expr_stmt|;
name|cmd
operator|.
name|solrDoc
operator|.
name|addField
argument_list|(
literal|"firstName"
argument_list|,
literal|"Tom"
argument_list|)
expr_stmt|;
name|cmd
operator|.
name|solrDoc
operator|.
name|addField
argument_list|(
literal|"lastName"
argument_list|,
literal|"Cruise"
argument_list|)
expr_stmt|;
operator|new
name|TemplateUpdateProcessorFactory
argument_list|()
operator|.
name|getInstance
argument_list|(
name|cmd
operator|.
name|getReq
argument_list|()
argument_list|,
operator|new
name|SolrQueryResponse
argument_list|()
argument_list|,
literal|null
argument_list|)
operator|.
name|processAdd
argument_list|(
name|cmd
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Tom_Cruise"
argument_list|,
name|cmd
operator|.
name|solrDoc
operator|.
name|getFieldValue
argument_list|(
literal|"id"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Cruise_Tom"
argument_list|,
name|cmd
operator|.
name|solrDoc
operator|.
name|getFieldValue
argument_list|(
literal|"another"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Cruise_"
argument_list|,
name|cmd
operator|.
name|solrDoc
operator|.
name|getFieldValue
argument_list|(
literal|"missing"
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

